# Generated by Django 5.0.3 on 2024-04-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0003_department_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhar',
            fields=[
                ('aadhar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('issued_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('aadhar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='DBApp.adhar')),
            ],
        ),
    ]
