# Generated by Django 5.0.3 on 2024-04-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0005_child1_child2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duplicate',
            fields=[
            ],
            options={
                'ordering': ['salary'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('DBApp.employee',),
        ),
    ]
