# Generated by Django 5.0.3 on 2024-04-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0007_base2_cars_alter_duplicate_options_child3_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
