# Generated by Django 5.0.3 on 2024-05-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('quantity', models.CharField(max_length=20)),
                ('total', models.FloatField()),
            ],
        ),
    ]
