# Generated by Django 5.0.3 on 2024-05-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='item',
            new_name='items',
        ),
    ]
